name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      task:
        type: choice
        options: [release, test-release]
        default: release
        description: Release to PyPI or TestPyPI.

permissions:
  contents: read

jobs:
  test:
    # run test.yml first to ensure that the test suite is passing
    uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install uv.
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Build source distribution and wheel
        run: |
          uv build

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.*

  release:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/custodian
    permissions:
      # For PyPI trusted publishing
      id-token: write
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist

      - name: Publish to PyPI or TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
